USE eol_prod;

insert into `feature_actions`(`Action_id`,`Title`,`feature_id`,`Action_Type`) values (1,'Send email/sms',1,'2 Way');
insert into `feature_actions`(`Action_id`,`Title`,`feature_id`,`Action_Type`) values (2,'Delete',1,'1 Way');
insert into `feature_actions`(`Action_id`,`Title`,`feature_id`,`Action_Type`) values (3,'Add',1,'1 Way');
insert into `feature_actions`(`Action_id`,`Title`,`feature_id`,`Action_Type`) values (4,'Reply/Forward',2,'2 Way');
insert into `feature_actions`(`Action_id`,`Title`,`feature_id`,`Action_Type`) values (5,'View',2,'1 Way');
insert into `feature_actions`(`Action_id`,`Title`,`feature_id`,`Action_Type`) values (6,'Delete',2,'1 Way');
insert into `feature_actions`(`Action_id`,`Title`,`feature_id`,`Action_Type`) values (7,'Create New',2,'2 Way');
insert into `feature_actions`(`Action_id`,`Title`,`feature_id`,`Action_Type`) values (8,'Create',3,'1 Way');
insert into `feature_actions`(`Action_id`,`Title`,`feature_id`,`Action_Type`) values (9,'View',4,'2 Way');
insert into `feature_actions`(`Action_id`,`Title`,`feature_id`,`Action_Type`) values (10,'Share',5,'2 Way');
insert into `feature_actions`(`Action_id`,`Title`,`feature_id`,`Action_Type`) values (11,'Upload',11,'1 Way');
insert into `feature_actions`(`Action_id`,`Title`,`feature_id`,`Action_Type`) values (12,'View',12,'1 Way');
insert into `feature_actions`(`Action_id`,`Title`,`feature_id`,`Action_Type`) values (13,'View',14,'1 Way');
insert into `feature_actions`(`Action_id`,`Title`,`feature_id`,`Action_Type`) values (14,'Create',16,'2 Way');
insert into `feature_actions`(`Action_id`,`Title`,`feature_id`,`Action_Type`) values (15,'Share',30,'2 Way');
insert into `feature_actions`(`Action_id`,`Title`,`feature_id`,`Action_Type`) values (16,'Create',30,'1 Way');
insert into `feature_actions`(`Action_id`,`Title`,`feature_id`,`Action_Type`) values (17,'Create',6,'1 Way');
insert into `feature_actions`(`Action_id`,`Title`,`feature_id`,`Action_Type`) values (18,'View',6,'2 Way');
insert into `feature_actions`(`Action_id`,`Title`,`feature_id`,`Action_Type`) values (19,'View',1,'2 Way');
insert into `feature_actions`(`Action_id`,`Title`,`feature_id`,`Action_Type`) values (20,'Delete',3,'1 Way');
insert into `feature_actions`(`Action_id`,`Title`,`feature_id`,`Action_Type`) values (21,'Edit',3,'1 Way');
insert into `feature_actions`(`Action_id`,`Title`,`feature_id`,`Action_Type`) values (22,'View',3,'2 Way');
insert into `feature_actions`(`Action_id`,`Title`,`feature_id`,`Action_Type`) values (23,'Create',4,'1 Way');
insert into `feature_actions`(`Action_id`,`Title`,`feature_id`,`Action_Type`) values (24,'Edit',4,'1 Way');
insert into `feature_actions`(`Action_id`,`Title`,`feature_id`,`Action_Type`) values (25,'Delete',4,'1 Way');
insert into `feature_actions`(`Action_id`,`Title`,`feature_id`,`Action_Type`) values (26,'Share',4,'2 Way');
insert into `feature_actions`(`Action_id`,`Title`,`feature_id`,`Action_Type`) values (27,'Like',6,'1 Way');
insert into `feature_actions`(`Action_id`,`Title`,`feature_id`,`Action_Type`) values (28,'Comment',6,'1 Way');
insert into `feature_actions`(`Action_id`,`Title`,`feature_id`,`Action_Type`) values (29,'Share',6,'2 Way');
